[GLOBAL]
pants_version = "2.8.0.dev3"
pantsrc = false

backend_packages.add = [
  "pants.backend.experimental.java",
]

[anonymous-telemetry]
enabled = true
repo_id = "1F6A0F61-C73B-4A9A-B936-14D1384EA3BB"
